---
- name: Configure Docker on Deployserver
  hosts: all
  become: true
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Python3 and pip
      apt:
        name: python3-pip
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Pull Docker image from DockerHub
      docker_image:
        name: shoaibpathan/insureme
        source: pull

    - name: Run Docker container
      docker_container:
        name: insureme_container
        image: shoaibpathan/insureme:latest
        state: started
        restart_policy: always
        ports:
          - "8084:8081"
